name: Deploy Hugo Site to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes if used as submodules
          fetch-depth: 0    # Fetch all history for Git info

      # Set up Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'  # Or specify a version, e.g., '0.134.2'
          extended: true          # Use extended Hugo for Sass/SCSS if needed

      # Build the Hugo site
      - name: Build Hugo
        run: hugo --minify --destination ./_site --logLevel info
        env:
          HUGO_ENV: production

      # Create .nojekyll file
      - name: Create .nojekyll
        run: touch ./_site/.nojekyll

      # Deploy to GitHub Pages
      - name: Deploy
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact: _site